/**
 * Root layout of the application with Sidebar and Header integration.
 */

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header"; // Header component

/**
 * Metadata for the application.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout component.
 * Provides a consistent layout with a Sidebar, Header, and Content area.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen overflow-hidden flex flex-col">
        {/* Header (spans full width) */}
        <Header />

        <div className="flex flex-1">
          {/* Navbar below Header */}
          <Navbar />

          {/* Main Content Area */}
          <main className="flex-1 overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
